name: publish

on:
  release:
    types: [ published ]

jobs:
  publish-dist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install build tools
      run: |
        python -m pip install hatch
    - name: Build distributions
      run: |
        hatch build
    - name: Publish distributions
      env:
        HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
      run: |
        hatch publish
