# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.descriptor import (
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class Result(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> Result: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[Result]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, Result]]: ...
SUCCESS = typing___cast(Result, 0)
ERROR_RESPONSE = typing___cast(Result, 1)

class AppendRequest(google___protobuf___message___Message):
    user = ... # type: typing___Text
    sender = ... # type: typing___Text
    recipient = ... # type: typing___Text
    mailbox = ... # type: typing___Text
    data = ... # type: bytes
    flags = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    when = ... # type: int

    def __init__(self,
        user : typing___Optional[typing___Text] = None,
        sender : typing___Optional[typing___Text] = None,
        recipient : typing___Optional[typing___Text] = None,
        mailbox : typing___Optional[typing___Text] = None,
        data : typing___Optional[bytes] = None,
        flags : typing___Optional[typing___Iterable[typing___Text]] = None,
        when : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> AppendRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class AppendResponse(google___protobuf___message___Message):
    result = ... # type: Result
    error_type = ... # type: typing___Text
    error_response = ... # type: bytes
    mailbox = ... # type: typing___Text
    validity = ... # type: int
    uid = ... # type: int

    def __init__(self,
        result : typing___Optional[Result] = None,
        error_type : typing___Optional[typing___Text] = None,
        error_response : typing___Optional[bytes] = None,
        mailbox : typing___Optional[typing___Text] = None,
        validity : typing___Optional[int] = None,
        uid : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> AppendResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
