# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Result(int):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> Result: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[Result]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, Result]]: ...
    SUCCESS = typing___cast(Result, 0)
    ERROR_RESPONSE = typing___cast(Result, 1)
SUCCESS = typing___cast(Result, 0)
ERROR_RESPONSE = typing___cast(Result, 1)

class AppendRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    user = ... # type: typing___Text
    sender = ... # type: typing___Text
    recipient = ... # type: typing___Text
    mailbox = ... # type: typing___Text
    data = ... # type: bytes
    flags = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    when = ... # type: int

    def __init__(self,
        *,
        user : typing___Optional[typing___Text] = None,
        sender : typing___Optional[typing___Text] = None,
        recipient : typing___Optional[typing___Text] = None,
        mailbox : typing___Optional[typing___Text] = None,
        data : typing___Optional[bytes] = None,
        flags : typing___Optional[typing___Iterable[typing___Text]] = None,
        when : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> AppendRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"data",u"flags",u"mailbox",u"recipient",u"sender",u"user",u"when"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"data",b"data",u"flags",b"flags",u"mailbox",b"mailbox",u"recipient",b"recipient",u"sender",b"sender",u"user",b"user",u"when",b"when"]) -> None: ...

class AppendResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    result = ... # type: Result
    error_type = ... # type: typing___Text
    error_response = ... # type: bytes
    mailbox = ... # type: typing___Text
    validity = ... # type: int
    uid = ... # type: int

    def __init__(self,
        *,
        result : typing___Optional[Result] = None,
        error_type : typing___Optional[typing___Text] = None,
        error_response : typing___Optional[bytes] = None,
        mailbox : typing___Optional[typing___Text] = None,
        validity : typing___Optional[int] = None,
        uid : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> AppendResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"error_response",u"error_type",u"mailbox",u"result",u"uid",u"validity"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"error_response",b"error_response",u"error_type",b"error_type",u"mailbox",b"mailbox",u"result",b"result",u"uid",b"uid",u"validity",b"validity"]) -> None: ...
